spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/lightspace?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
#    password: lightspace
    
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 50
        max-wait: -1
        max-idle: 30
        min-idle: 2
  main:
    allow-bean-definition-overriding: true
  
  
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: false  
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
        
server:    
  servlet:
    context-path: /lightspace    
    

